### ISSUE TITLE
Roadmap / v2.0.0

### ISSUE THREAD

**Issue by timcraft** [readysteady/mailgunner#2]
Changes I would like to see before v2.0.0, and working towards:
- [x] allow :domain option to be nil
- [x] eliminate faux development dependency
- [x] add method for sending a Mail message in MIME format
- [x] add ActionMailer integration
- [x] remove deprecated json methods
- [x] remove deprecated get_log/mailbox methods
- [x] remove deprecated :json option
- [x] remove Mailgunner::Response class and add exception classes
- [x] switch to webmock
- [x] add changelog

Feedback and other suggestions welcome.
